### PR TITLE
Design for emoji-lookup

### PR DESCRIPTION
**Pull request by degiorgioo**
Hi @tourn , I had some sleepless nights 😄 , thus I decided to create a design for your cool emoji-lookup. Please have a look on this, hope you like it.  🎉 🎉

### CODE REVIEW

**Comment by gummibjorn** [comment]
really looking forward to that one! please merge

**Comment by tourn** [comment]
Man, that looks sweet. I changed one thing, it now displays the name of the emoji on the copy button: 
image

Cheers :beers:

**Comment by degiorgioo** [comment]
Great. Thanks Man. Yeah, that was also my first idea and I realised that in some cases, for example if you search 'triangle', the name of the shorteners are a way to long. This causes problems in layout but this is a very small issue. 

Great collaboration, next goal is to improve the website on mobile devices. Actually it's not very enjoyable. Should we do that or is it a way to much @tourn ?

**Comment by tourn** [comment]
>  if you search 'triangle', the name of the shorteners are a way to long.

Yeah, you're right. Maybe we should let the shorthands be able to break to a new line on `_`?

> next goal is to improve the website on mobile devices. Actually it's not very enjoyable. 

I don't find it so bad on mobile, but if you have any ideas, feel free to change it up :)

**Comment by degiorgioo** [comment]
> Yeah, you're right. Maybe we should let the shorthands be able to break to a new line on _?

Yeah mate, good idea. I will check it. 

> I don't find it so bad on mobile, but if you have any ideas, feel free to change it up :)

I have some Ideas but let me check first, if something like that is needed. 

cheers 🍻

**Pull request merged**
